version: '2'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - /Users/danielnikulin/DBs/sqlite/data-dev.sqlite:/app/data-dev.sqlite3
    links:
      - redis
      - mongo
  mongo:
      image: mongo
      ports:
      - 27017:27017
      volumes:
        - /Users/danielnikulin/DBs/mongodata/db:/data/db
  redis:
      image: redis
      ports:
        - 6379:6379
      volumes:
        - /Users/danielnikulin/DBs/redis/:/var/lib/redis/